apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: product-redis
  name: product-redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: product-redis
status:
  loadBalancer: {}
