apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: user-db
  name: user-db
spec:
  ports:
    - name: "8081"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: user-db
status:
  loadBalancer: {}
