apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xotomicro-back-auth-service
  name: xotomicro-back-auth-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: xotomicro-back-auth-service
status:
  loadBalancer: {}
