apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xotomicro-back-event-service
  name: xotomicro-back-event-service
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    io.kompose.service: xotomicro-back-event-service
status:
  loadBalancer: {}
