apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: xotomicro-back-event-service
  name: xotomicro-back-event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: xotomicro-back-event-service
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: xotomicro-back-event-service
    spec:
      serviceAccountName: default
      containers:
        - image: xotomicro-back-event-service
          name: xotomicro-back-event-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: PROFILE
              value: docker
            - name: ENV
              value: production
          resources: {}
      restartPolicy: Always
status: {}
