apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xotomicro-back-internal-gateway-system
  name: xotomicro-back-internal-gateway-system
spec:
  type: NodePort
  ports:
    - name: "8070"
      port: 8070
      targetPort: 8080
  selector:
    io.kompose.service: xotomicro-back-internal-gateway-system
status:
  loadBalancer: {}
