apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xotomicro-back-order-service
  name: xotomicro-back-order-service
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
  selector:
    io.kompose.service: xotomicro-back-order-service
status:
  loadBalancer: {}
