apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xotomicro-back-product-service
  name: xotomicro-back-product-service
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: xotomicro-back-product-service
status:
  loadBalancer: {}
